version: "3.8"

services:
  web:
    image: httpd:alpine
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/:ro
